kakao:
  client:
    id: 10591b4c28e1de84d6fd5da8ec5c3467
    secret: P58Ag0P2sjaW2hlhtxNJn1WD2QJqZnD6
  redirect-url: http://localhost:8080/api/auth/login/oauth2/code/kakao


runky:
  security:
    cookie:
      domain: localhost
      secure: true
      http-only: true
      same-site: none
    jwt:
      secretKey: testSecretKey20230327testSecretKey20230327testSecretKey20230327
      expirationTime:
        accessTokenMinutes: 60
        refreshTokenHours: 24
      refresh-token:
        pepper: refreshSecret20250812refreshSecret20250812refreshSecret20250812
server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  application:
    name: runky
  profiles:
    active: local  # 기본 활성 프로필 (local or prod)
  config:
    import:
      - jpa.yml

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: prod
