spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chzzkzzal?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: your_db_username
    password: your_db_password

    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 30000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
