spring:
  application:
    name: runky

  profiles:
    active: local  # 기본 활성 프로필 (local or prod)

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

springdoc:
    use-fqn: true
    swagger-ui: /swagger-ui.html
